### ISSUE TITLE
Linguistic features

### ISSUE THREAD

**Issue by josejuanmartinez** [ccoreilly/spacy-catala#1]
Hi Ciaran!

I'm testing the catalan LM for spacy 2.1.0, and I only get to work the lemma from the linguistic features. Are the rest included, like POS, TAG, ENT_TYPE ?

![image](https://user-images.githubusercontent.com/36634572/90174905-f7cdf100-dda6-11ea-805b-b0f52f17bcfc.png)

Thank you!

**Comment by ccoreilly** [comment]
Hola Jose!

What model version are you using? I have no problems with spacy 2.3 and the latest model (0.1.0 which is trained on spacy 2.2 but still, there are no issues).

```
>>> for token in nlp('Bon dia tinga vosté'): print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_, token.shape_, token.is_alpha, token.is_stop)
...
Bon Bon PROPN PROPN nsubj Xxx True False
dia dia NOUN NOUN flat xxx True False
tinga tenir VERB VERB ROOT xxxx True False
vosté vosté PRON PRON xcomp xxxx True False
```

Entity recognition is not very good as I had little training data when I created the model but the tagger and parser are good enough for my use case.

```
>>> for token in nlp('La Generalitat de Catalunya té els seus orígens en les Corts Catalanes, les quals, durant el regnat de Jaume I el Conqueridor (1208-1276), es reunien convocades pel rei com a representatives dels estaments socials de l\'època'): print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_, token.shape_, token.is_alpha, token.is_stop, token.ent_type_)
...
La La DET DET det Xx True True
Generalitat Generalitat PROPN PROPN nsubj Xxxxx True False ORG
de de ADP ADP case xx True True ORG
Catalunya Catalunya PROPN PROPN flat Xxxxx True False ORG
té tenir VERB VERB ROOT xx True False
els ell DET DET det xxx True True
seus seure DET DET det xxxx True True
orígens origen NOUN NOUN obj xxxx True False
en en ADP ADP case xx True True
les ell DET DET det xxx True True
Corts Corts PROPN PROPN obl Xxxxx True False ORG
Catalanes Catalanes PROPN PROPN flat Xxxxx True False ORG
, , PUNCT PUNCT punct , False False
les ell DET DET det xxx True True
quals qual PRON PRON nsubj xxxx True True
, , PUNCT PUNCT punct , False False
durant durar ADP ADP case xxxx True True
el ell DET DET det xx True True
regnat regnar NOUN NOUN obl xxxx True False
de de ADP ADP case xx True True
Jaume Jaume PROPN PROPN nmod Xxxxx True False PER
I I CCONJ CCONJ cc X True True PER
el ell DET DET det xx True True PER
Conqueridor Conqueridor PROPN PROPN conj Xxxxx True False PER
( ( PUNCT PUNCT punct ( False False
1208 1208 NOUN NOUN appos dddd False False
- - PUNCT PUNCT punct - False False
1276 1276 NOUN NOUN appos dddd False False G
) ) PUNCT PUNCT punct ) False False
, , PUNCT PUNCT punct , False False
es ell PRON PRON obj xx True True
reunien reunir VERB VERB acl xxxx True False
convocades convocar ADJ ADJ obj xxxx True False
pel pel ADP ADP case xxx True True
rei rei NOUN NOUN obj xxx True False
com com SCONJ SCONJ case xxx True True
a a ADP ADP fixed x True True
representatives representatiu NOUN NOUN obj xxxx True False
dels dels ADP ADP case xxxx True True
estaments estament NOUN NOUN nmod xxxx True False ORG
socials social ADJ ADJ amod xxxx True False ORG
de de ADP ADP case xx True True ORG
l' ell DET DET det x' False False ORG
època època NOUN NOUN nmod xxxx True False ORG
```

You can see it detects Generalitat de Catalunya and Corts Catalanes as ORG (Organization) and Jaume I el Conqueridor as PER (Person) but it also detects estaments socials de l'època as ORG (which is disputable). There are also other NER tags in the model which are due to an unclean dataset (this is a pending task...).

**Comment by josejuanmartinez** [comment]
Hola Ciaran!

I was just installing as per what the Readme.md (0.0.2) in master says. Then I got the results I sent in this issue, and a warning saying that the model is not compatible with spacy 2.3.0. So I created a venv with spacy 2.1.0 and tried again, again same results (only lemma is ok), but without the warning.

I will try with the 0.0.3 in releases and let you know.

Thank you for your time!

**Comment by josejuanmartinez** [comment]
Ciaran,

the 3.0.0 version already works, except the lemma. I've tried in Spacy 2.3.0 (throws again a warning saying that the model was trained for 2.2.0, but anyway it works), and also for 2.2.0, and same results.

Any idea?
![image](https://user-images.githubusercontent.com/36634572/90251057-6d849c00-de3d-11ea-8f8e-22fcc2bab97c.png)

**Comment by ccoreilly** [comment]
Hi Jose,

sorry for the late reply. You're right that version 0.3.0 does not include the lemma. Version 0.1.0 of the model (the latest release) does but it has some issues as well.

I am planning on cleaning up the dataset and releasing a new version so I'll look into fixing it.

**Comment by josejuanmartinez** [comment]
Ok, thank you !

**Comment by ccoreilly** [comment]
Hi Jose,

sorry for my late reply but I had no time until now... I just published a new medium sized model trained on spaCy 2.3.2. Would you mind trying it out?

https://github.com/ccoreilly/spacy-catala/releases/tag/ca_fasttext_wiki_md-1.0.0

I will release the large model later today.
