### ISSUE TITLE
Error installing v 1.0.0

### ISSUE THREAD

**Issue by jmsabate** [ccoreilly/spacy-catala#2]
Hi Ciaran,

I'm trying to install version 1.0.0. It doesn't work! (404)

Could it be that the correct address is:
pip install https://github.com/ccoreilly/spacy-catala/releases/download/ca_fasttext_wiki_md-1.0.0/ca_fasttext_wiki_md-1.0.0-py3-none-any.whl

instead of:
pip install https://github.com/ccoreilly/spacy-catala/releases/download/1.0.0/ca_fasttext_wiki_md-1.0.0-py3-none-any.whl

Thanks!

**Comment by ccoreilly** [comment]
Hello!

You're totally right, if you want to install the medium sized model:

`pip install https://github.com/ccoreilly/spacy-catala/releases/download/ca_fasttext_wiki_md-1.0.0/ca_fasttext_wiki_md-1.0.0-py3-none-any.whl`

For the large model:

`pip install https://github.com/ccoreilly/spacy-catala/releases/download/ca_fasttext_wiki_lg-1.0.0/ca_fasttext_wiki_lg-1.0.0-py3-none-any.whl`

Thanks for the hint, I'll update the README accordingly
