### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by juleur** [ccoreilly/spacy-catala#3]
Hola Ciaran,

I encountered this error when I ran my code.

[![warning.png](https://i.postimg.cc/XN5ff16G/warning.png)](https://postimg.cc/py25xZTR)

[![err.png](https://i.postimg.cc/d0XCdrWj/err.png)](https://postimg.cc/rd1z202D)

> Python 3.8.6

> spaCy version 3.0.1

**Comment by ccoreilly** [comment]
Hi Julien,

spaCy 3.0 was released recently and I am not sure if older models are 100% compatible. I will look into updating the model, thanks for sharing.

Until then I can only suggest using the 2.3.5 version of spacy or older.
