### ISSUE TITLE
Es la llicència adequada?

### ISSUE THREAD

**Issue by jaumemir** [ccoreilly/spacy-catala#4]
Hola @ccoreilly, abans de res, felicitar-te per la teva tasca de desevolupar eines NLP per al català. Crec que es un esforç molt necessari per a la nostra llengua, pero permet-me fer-te una reflexió.

Veig que llicències el codi amb AGPL 3.0, la qual es bastant restrictiva per a una empresa, tant de desenvolupament de producte com la que implementi un projecte intern. Això contrasta amb la llicència de SPACY, que es la MIT.

Per tant els desenvolupadors que es guanyen la vida desenvolupant per tercers podran fer servir SPACY però no el teu model en català, doncs injecten una obligació - la de obligar a distribuir el codi font dels programes derivats - que els seus clients possiblement no voldran assumir.

A menys que tinguis una bona raó, crec que seria millor que el model català per Spacy compartís la mateixa llicència MIT que la llibreria. 

També seria bò que des del lloc de Spacy fos sencill trobar aquest projecte, per exemple fent-lo visible aqui: https://spacy.io/universe/category/models

**Comment by ccoreilly** [comment]
Hola Jaume!

gràcies per treure el tema de la llicència. Si et sóc sincer no tinc cap problema en canviar la llicència a una de més permisiva però no estic segur de poder.

El model català de l'spaCy ha estat entrenat amb les dades del corpus Ancora proporcionat per UniversalDependencies i [distribuït amb una llicència GPL3.0](https://github.com/UniversalDependencies/UD_Catalan-AnCora/blob/master/LICENSE.txt). Entenc que el model és doncs un derivat i s'ha de distribuir amb la mateixa llicència GPL3.0 o alternativament AGPL3.0 ja que són força intercanviables.

Podria canviar la llicència a GPL3.0, d'aquesta manera només cal distribuir el codi font si es distribueix el model juntament amb l'aplicació. Si no es vol compartir el codi font sempre hi ha l'alternativa de comunicar a l'usuari que ha de descarregar-se el model i posar-lo en una carpeta concreta o carregar-lo des de l'aplicació. D'aquesta manera, en no ser part de la distribució ni un derivat directe, no cal que el codi que fa servir el model es llicenciï sota GPL3.0.

Que en penses?

Pel que fa a fer que el projecte sigui fàcil de trobar: completament d'acord, però tinc entès que des del [projecte Aina](https://politiquesdigitals.gencat.cat/ca/tic/aina-el-projecte-per-garantir-el-catala-en-lera-digital/) estan preparant un model spaCy 3.0 amb molts més recursos i que s'espera sigui millor. Per tant crec que ara per ara no val la pena fer l'esforç de publicar-lo a pypi o la web de spacy si d'aquí 2-3 mesos ho faran ells amb un model millor.

**Comment by jaumemir** [comment]
Doncs si, tens tota la raó. No hi havia caigut.  En aquest cas es com dius, cal mantenir la GPL3.0 i el workaround que proposes es bastant habitual.
I de fet, si mires a https://opensource.org/licenses/category la GPL3.0 es una de les populars, mentre que la AGPL esta  a la llista de les no categoritzades.

Sobre l'Aina, jo sabia que estaven treballant en fer un model d'embeddings per al Català. El que no sabia es que l'integrarien com a model per a Spacy. Espero que el treguin ja per a Spacy 3.0 (a més de per a 2.3.x)
